# @package algo
_convert_: all
_target_: stable_baselines3.SAC
policy: "MlpPolicy"

# Training hyperparameters
learning_rate: 0.0003
batch_size: 256
gamma: 0.99
tau: 0.005
ent_coef: "auto"
train_freq: 1
gradient_steps: 1
verbose: 1
