defaults:
  - algo: bpo/atari
  - env: atari
  - _self_

wandb:
  project: BPO
  entity: {your-entity-name}
  monitor_gym: true
  save_code: true

training:
  total_timesteps: 40_000_000
  gradient_save_freq: 100_000
  n_envs: 8
  seed: 42
