[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Bounded-Policy-Optimization"
version = "0.1.0"
readme = "README.md"
requires-python = "==3.10.20"

# Core deps: just what both backends need
dependencies = [
  "hydra-core",
  "swig",
  "wandb",
  "moviepy",
  "ale_py",
  "gymnasium[mujoco]>=1.0.0",
]

[project.optional-dependencies]
sb3 = [
  "stable-baselines3[extra]",
  "setuptools<70.0.0",
]
isaaclab = [
  "torch==2.5.1",
  "torchvision==0.20.1",
  "setuptools<70.0.0",
  "wheel",
  "poetry-core"
]
ttrl = [
  "setuptools<70.0.0",
  "accelerate",
  "codetiming",
  "datasets",
  "dill",
  "hydra-core",
  "numpy",
  "pandas",
  "peft",
  "pyarrow>=19.0.0",
  "pybind11",
  "pylatexenc",
  "ray[default]>=2.41.0",
  "torchdata",
  "tensordict<=0.6.2",
  "transformers",
  "wandb",
  "packaging>=20.0",
  "latex2sympy2_extended",
  "math_verify",
]
all = [
  "stable-baselines3[extra]",
  "torch==2.5.1",
  "torchvision==0.20.1",
  "setuptools<70.0.0",
  "wheel",
  "poetry-core",
  "accelerate",
  "codetiming",
  "datasets",
  "dill",
  "numpy",
  "pandas",
  "peft",
  "pyarrow>=19.0.0",
  "pybind11",
  "pylatexenc",
  "ray[default]>=2.41.0",
  "torchdata",
  "tensordict<=0.6.2",
  "transformers",
  "packaging>=20.0",
  "latex2sympy2_extended",
  "math_verify",
]

[tool.uv]
build-constraint-dependencies = ["setuptools<70.0.0"]
required-environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'"
]

[tool.uv.extra-build-dependencies]
flatdict = ["setuptools<70.0.0"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
verl = [
  "version/*",
  "trainer/config/*.yaml"
]

